spring.application.name=birthday-tracker

spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,file:/static/
spring.mvc.static-path-pattern=/**

spring.web.resources.cache.period=0
spring.web.resources.add-mappings=true
server.servlet.context-path=/

spring.datasource.url=jdbc:postgresql://localhost:5432/birthdaytracker
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

interval-in-cron = 0 15 10 * * *


spring.mail.host=${EMAIL_HOST:smtp.mail.ru}
spring.mail.port=${EMAIL_PORT:465}
spring.mail.username=student_test_dance@mail.ru
spring.mail.password="6mMjoxlxQTofYftgzqY7"
spring.mail.protocol=${EMAIL_PROTOCOL:smtps}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.enable=true

app.email.from=student_test_dance@mail.ru
app.email.from-name=Birthday Tracker
app.email.enabled=true

app.photos.dir=/data/photos
app.photos.url=/photos

